### ISSUE TITLE
Missing items in main_CalciumPipeline

### ISSUE THREAD

**Issue by AmosG8** [pbl007/PBLabToolkit#1]
Main unsolved issues with the current pipeline:

1. Requires all loaded files to be of the same FOV.
2. Loading `StimVector` and `SpeedVector` into the EP_FILES struct (in `getDataFromDir`).
3. In `AG_slice_EP_variables`: Currently the code assumes that we have 1000 `Stim` samples per frame. After checking it appears that it samples 1000 times per second. 
4. Make sure that the time that passes between subsequent stimuli is indeed at least 15 secs and change the way it marks the `ResponseWindow`.
5. Classify frames to run and stand frames (lines 70-80) in `AG_slice_EP_variables`.
6.

**Comment by HagaiHargil** [comment]
For now, we still have no idea if the higher spikes are the true stimuli, or if the lower ones are. This will become important pretty soon. :)

The rest of the things in this issue are done.
